name: Deploy to AWS S3 + CloudFront

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Doppler
        uses: dopplerhq/cli-action@v1
        with:
          doppler-token: ${{ secrets.DOPPLER_TOKEN }}

      - name: Load environment variables
        run: doppler secrets download --format env --no-file > .env

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to S3
        run: |
          aws s3 sync dist/ s3://$AWS_BUCKET --region $AWS_REGION --delete

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id $CLOUDFRONT_DISTRIBUTION_ID \
            --paths "/*"
